---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  namespace: app-workload
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api
  unhealthyPodEvictionPolicy: AlwaysAllow

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: app-workload
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
  unhealthyPodEvictionPolicy: AlwaysAllow

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nats-pdb
  namespace: app-workload
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nats

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valkey-pdb
  namespace: app-workload
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
